# Generated by Django 4.1 on 2024-05-21 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('plot', models.CharField(max_length=1000)),
                ('rate', models.IntegerField()),
                ('director', models.CharField(max_length=50)),
                ('actors', models.JSONField()),
                ('genres', models.JSONField()),
                ('release_date', models.DateField(null=True)),
                ('post_img_path', models.CharField(max_length=100)),
                ('background_img_path', models.CharField(max_length=100)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.movieinfo')),
            ],
        ),
    ]
