# Generated by Django 4.1 on 2024-07-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieInfo',
        ),
    ]
