# Generated by Django 4.1 on 2024-05-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('release_date', models.DateField(null=True)),
                ('post_img_path', models.CharField(max_length=100)),
            ],
        ),
    ]
