# Generated by Django 4.1 on 2024-07-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='rate',
            new_name='runtime',
        ),
        migrations.RemoveField(
            model_name='movieinfo',
            name='post_img_path',
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='actors',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='adult',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='backdrop_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='director',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='genres',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='overview',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='popularity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='poster_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='vote_average',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='vote_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
